name: ecommerce_app
description: A new Flutter ecommerce application.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.5
  auto_route: ^10.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_riverpod: ^2.6.1
  firebase_remote_config: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  flutter_stripe: ^11.5.0
  google_maps_flutter: ^2.12.3
  sizer: ^3.0.0
  camera: ^0.11.2
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  logger: ^2.6.1
  shimmer: ^3.0.0
  badges: ^3.1.2
  url_launcher: ^6.3.2
  google_fonts: ^6.3.0
  flutter_svg: ^2.0.13
  cached_network_image: ^3.4.1
  mockito: ^5.5.0
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/app_icon.png
  - assets/images/apple_pay.png
  - assets/images/facebook.png
  - assets/images/google_pay.png
  - assets/images/google.png
  - assets/images/img_app_logo.svg
  - assets/images/no-image.jpg
  - assets/images/paypal.png
  - assets/images/sad_face.svg
  - assets/images/splash_background.jpeg
