name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.12.3
  url_launcher: ^6.3.1
  flutter_credit_card: ^4.1.0
  flutter_stripe: ^11.5.0
  paypal_sdk: ^1.0.11
  shared_preferences: ^2.5.3
  google_sign_in: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.2
  supabase_flutter: ^2.9.1 
  badges: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Firebase - Updated to compatible versions
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0  # Updated to resolve conflict
  cloud_firestore: ^6.0.0
  firebase_remote_config: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/splash_background.jpeg
    - assets/images/apple_pay.png
    - assets/images/facebook.png
    - assets/images/google_pay.png
    - assets/images/google.png
    - assets/images/paypal.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  background_image: assets/images/splash_background.jpeg
  image: assets/images/app_icon.png
  android: true
  ios: true
  android_gravity: center
  fullscreen: true