// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6yBJlSTBh6oc9Tr7hpi9hJvr9ZoOVQno',
    appId: '1:1010865686579:web:54bba3f8f151c53ce63b46',
    messagingSenderId: '1010865686579',
    projectId: 'farmers-bracket-a9141',
    authDomain: 'farmers-bracket-a9141.firebaseapp.com',
    storageBucket: 'farmers-bracket-a9141.firebasestorage.app',
    measurementId: 'G-ECLMQZ83F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCBPxRzBVueiZjqvRz_Zmq3t8BIsA9x7E',
    appId: '1:1010865686579:android:ae9f1874496d23bbe63b46',
    messagingSenderId: '1010865686579',
    projectId: 'farmers-bracket-a9141',
    storageBucket: 'farmers-bracket-a9141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Qf9R1_GTteme1aydn424FEuBqQG6jcM',
    appId: '1:1010865686579:ios:e4567275a545e9bbe63b46',
    messagingSenderId: '1010865686579',
    projectId: 'farmers-bracket-a9141',
    storageBucket: 'farmers-bracket-a9141.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Qf9R1_GTteme1aydn424FEuBqQG6jcM',
    appId: '1:1010865686579:ios:e4567275a545e9bbe63b46',
    messagingSenderId: '1010865686579',
    projectId: 'farmers-bracket-a9141',
    storageBucket: 'farmers-bracket-a9141.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6yBJlSTBh6oc9Tr7hpi9hJvr9ZoOVQno',
    appId: '1:1010865686579:web:25ba707af97594dfe63b46',
    messagingSenderId: '1010865686579',
    projectId: 'farmers-bracket-a9141',
    authDomain: 'farmers-bracket-a9141.firebaseapp.com',
    storageBucket: 'farmers-bracket-a9141.firebasestorage.app',
    measurementId: 'G-4HSWX7PH21',
  );

}